apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-4vig
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-4vig@sha256:9c6a9d1b3a3ed0229d7ba2ae55a4b23e57e434a099a0523ed582ce7bf2ffbced
        name: my-nodejs
        resources: {}
status: {}
